README.md
Reverts MintCN/linux-insides-zh#28
=> Revert "Chap1 2 status update  #27"

CONTRIBUTING.md
Reverts MintCN/linux-insides-zh#30
=> Revert "Contributing fix"

README.md
Update the README file to mark the chap1_2 finish
=> pr for finish chap1_2

README.md
=> update chap1_1 to finish

README.md
=> 申请翻译 1-5 #23

README.md, SyncPrim/sync-3.md, contributors.md
=> Add translation

SysCall/syscall-1.md, SysCall/syscall-2.md, SysCall/syscall-3.md, SysCall/syscall-4.md
=> 翻译 SysCall

README.md
=> 申请翻译 6.1 节的内容

README.md
Request to translate chapter 9 #81
=> Update README.md status

Concepts/cpumask.md, Concepts/initcall.md, Concepts/per-cpu.md
=> ch 9 merged from 0xAX

README.md
=> modify 6.2

README.md
申请翻译第13.3节，翻译完成后将会把中文版本和其对应的英文版本一同提交。
=> Apply for translating 13.3.

README.md, contributors.md
"10.2 radix-tree" 贡献者有误，oska874 同学是 “10.1 双向链表” 的贡献者 :)
=> update 10.2 contributor

Initialization/linux-initialization-1.md
Help implement translation task of linux initialization part 1 and fix some typos.
=> Help implement translation and fix some typoes

Cgroups/cgroups1.md
1. 第一个 "control group" 翻译成中文
2. 更正一个英文冒号
**抱歉，提交 PR 之前 review 了好多遍，还是有点不尽完美。
目前 没再发现 让自己不满意的地方了，麻烦啦**
=> 15.1 翻译修订。第一个 "control group" 翻译成中文；更正一个英文冒号。

README.md
=> Update translation status

Initialization/linux-initialization-5.md, README.md
Sync up with the upstream English version and modified the status of chapter 2.5 in the README.md
=> Update the linux-initialization-5.md to the latest English repo version

README.md
=> Update readme.MD for claiming chapter 3.2

CONTRIBUTORS.md, Interrupts/linux-interrupts-2.md, README.md
=> Complete translation of 3-2

README.md
Request to checkout chapter 5.6.
And will do the reset parts of Section 5 then.
Signed-off-by: Yi Sun <syqust@gmail.com>
=> README: Checkout Chapter 5.6

Initialization/linux-initialization-4.md
Signed-off-by: Qiao Yongchang <qiaoyongchang@gmail.com>
=> fix some typo

README.md, SyncPrim/linux-sync-4.md
=> Request for translate chapter 6.4

CONTRIBUTORS.md, README.md, SyncPrim/linux-sync-4.md
这个 patch 做了三个改动
1. 完成翻译了互斥锁内文 ( SyncPrim/linux-sync-4.md
2. 将我自己加入到贡献者 ( CONTRIBUTORS.md
3. 更新翻译进度列表 ( README.md
感谢审核，翻译还真不简单啊QQ
=> MUTEX章节已翻译完成

Misc/linux-misc-3.md
修复该章节汇编代码错误，修改代码复制于上游仓库（https://github.com/0xAX/linux-insides/blob/master/Misc/linux-misc-3.md ），已在本地验证
=> fix asm code error in Misc/linux-misc-3.md

Timers/linux-timers-6.md
Signed-off-by: Yi Sun <syqust@gmail.com>
=> Tranlate linux-timers-6

MM/linux-mm-1.md
=> Fix mm_1.md

.github/ISSUE_TEMPLATE/1_translation_request.yaml
=> add: issue template

Booting/linux-bootstrap-1.md
=> fix: confusing expression

MM/linux-mm-2.md
=> fix mm_2.md

Booting/linux-bootstrap-4.md, DataStructures/linux-datastructures-3.md, Interrupts/linux-interrupts-4.md, Interrupts/linux-interrupts-5.md, SyncPrim/linux-sync-1.md, SyncPrim/linux-sync-2.md, SyncPrim/linux-sync-4.md, SyncPrim/linux-sync-5.md, Theory/linux-theory-3.md
fix #283 
update x86 ref link from x86.renejeschke.de to x86.hust.openatom.club
=> fix: update dead link x86.renejeschke.de

SysCall/linux-syscall-1.md, SysCall/linux-syscall-3.md
=> fix: link for markdown

Initialization/linux-initialization-7.md, TRANSLATION_STATUS.md
将 TRANSLATION_STATUS.md 2.7节状态修改为：正在进行 #297
=> Update Translate status
